name: Testing

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Setup uv
      uses: yezz123/setup-uv@v4
      
    - name: Install dependencies
      run: uv sync
      
    - name: Run pytest
      run: uv run pytest -v
